export const ComponentIDs = {
  addProjectCardBody: 'addProjectCardBody',
  addProjectMenuItem: 'addProjectMenuItem',
  addProjectFormName: 'addProjectFormName',
  addProjectFormPicture: 'addProjectFormPicture',
  addProjectFormHomePage: 'addProjectFormHomePage',
  addProjectFormDescription: 'addProjectFormDescription',
  addProjectFormInterests: 'addProjectFormInterests',
  addProjectFormParticipants: 'addProjectFormParticipants',
  addProjectFormSubmit: 'addProjectFormSubmit',
  basicNavbarNav: 'basicNavbarNav',
  currentUserDropdown: 'currentUserDropdown',
  currentUserDropdownSignOut: 'currentUserDropdownSignOut',
  filterFormInterests: 'filterFormInterests',
  filterFormSubmit: 'filterFormSubmit',
  filterMenuItem: 'filterMenuItem',
  editProfileCardBody: 'editProfileCardBody',
  editProfileFormFirstName: 'editProfileFormFirstName',
  editProfileFormLastName: 'editProfileFormLastName',
  editProfileFormBio: 'editProfileFormBio',
  editProfileFormSubmit: 'editProfileFormSubmit',
  editProfileMenuItem: 'editProfileMenuItem',
  interestsMenuItem: 'interestsMenuItem',
  landingMenuItem: 'landingMenuItem',
  loginDropdown: 'loginDropdown',
  loginDropdownSignIn: 'loginDropdownSignIn',
  loginDropdownSignUp: 'loginDropdownSignUp',
  profilesMenuItem: 'profilesMenuItem',
  projectsMenuItem: 'projectsMenuItem',
  signInCardBody: 'signInCardBody',
  signInFormAlert: 'signInFormAlert',
  signInFormEmail: 'signInFormEmail',
  signInFormPassword: 'signInFormPassword',
  signInFormSubmit: 'signInFormSubmit',
  signUpCardBody: 'signUpCardBody',
  signUpFormAlert: 'signUpFormAlert',
  signUpFormEmail: 'signUpFormEmail',
  signUpFormPassword: 'signUpFormPassword',
  signUpFormSubmit: 'signUpFormSubmit',
  singleProjectAddButton: 'singleProjectAddButton',
  singleProjectMenuItem: 'singleProjectMenuItem',
};

export const PageIDs = {
  addProjectPage: 'addProjectPage',
  filterPage: 'filterPage',
  editProfilePage: 'editProfilePage',
  interestsPage: 'interestsPage',
  landingPage: 'landingPage',
  notAuthorizedPage: 'notAuthorizedPage',
  notFoundPage: 'notFoundPage',
  profilesPage: 'profilesPage',
  projectsPage: 'projectsPage',
  signInPage: 'signInPage',
  signOutPage: 'signOutPage',
  signUpPage: 'signUpPage',
};
